Petit Optimisation
Margouta/PluginOpenMC pull request #241
Opened 2024-07-30 21:16 UTC by LucasB25

*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*:
yes
*Votre code se compile t-il en local ?*: 
yes

*Avez-vous supprimez les imports inutilisés ?*: 
oui
## Decrivez vos changements
Opti

2024-07-30 21:52 UTC, Margouta commented
fait en sorte que ça se compile stp

2024-07-30 21:57 UTC, Armibule commented
Je ne comprends pas trop ce que tu as modifié sur l'EventManager et aussi pourquoi tu as retiré les commentaires avec les chances de drops ?

2024-07-31 08:05 UTC, AxillityWasGay requested changes
Fix Code EventsManager,java pour compil

```java
import org.bukkit.Material;
import org.bukkit.attribute.Attribute;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Entity;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Monster;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.scheduler.BukkitRunnable;

import java.util.*;

public class EventsManager implements Listener {
    private static final int TERRIFYING_NIGHT = 0;
    // private static final int DROUGHT = 1;    // idea for another event

    private static final Map<String, Integer> EVENTS = new HashMap<String, Integer>() {{
        put("terrifingNight", TERRIFYING_NIGHT);
        // put("drought", DROUGHT);
    }};

    private final AywenCraftPlugin plugin;
    private final List<Integer> enabledEvents;
    private BukkitRunnable eventRunnable;

    public EventsManager(AywenCraftPlugin plugin, FileConfiguration config) {
        this.plugin = plugin;
        List<String> disabledEvents = (List<String>) config.getList("disabledEvents");
        if (disabledEvents == null) {
            disabledEvents = Collections.emptyList(); // Empty list if null
        }

        enabledEvents = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : EVENTS.entrySet()) {
            if (!disabledEvents.contains(entry.getKey())) {
                enabledEvents.add(entry.getValue());
            }
        }

        // Initialize your eventRunnable here based on enabledEvents or other logic
    }

    public void run() {
        // Your main logic for handling events
    }

    @EventHandler
    public void onMobDeath(EntityDeathEvent event) {
        Entity entity = event.getEntity();
        Random random = new Random();
        float randomFloat = random.nextFloat();

        ItemStack item;
        switch (entity.getType()) {
            case ZOMBIE:
                item = new ItemStack(Material.ZOMBIE_HEAD);
                break;
            case SKELETON:
                item = new ItemStack(Material.SKELETON_SKULL);
                break;
            case CREEPER:
                item = new ItemStack(Material.CREEPER_HEAD);
                break;
            default:
                item = null;
                break;
        }

        // Further processing of the item if needed
    }

    private void boostMonster(LivingEntity entity, World world) {
        // Your logic to boost monsters
    }
}

```

2024-07-31 08:07 UTC, AxenoDev commented
Ton code ne ce compile pas !

2024-08-01 14:49 UTC, AxenoDev commented
Ton code ne ce compile pas

2024-08-01 14:49 UTC, AxenoDev commented
et il y a des conflicts

2024-08-01 15:47 UTC, closed without merging